START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    CREATE TABLE "Professionals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "PhotoUrl" text NOT NULL,
        "CalendarColor" text NOT NULL,
        "Specialty" text,
        "Commission" numeric(5,2) NOT NULL,
        "Schedule" jsonb,
        "IsActive" boolean NOT NULL,
        "Order" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Professionals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    CREATE TABLE "ProfessionalServices" (
        "ProfessionalId" integer NOT NULL,
        "ServicesId" integer NOT NULL,
        CONSTRAINT "PK_ProfessionalServices" PRIMARY KEY ("ProfessionalId", "ServicesId"),
        CONSTRAINT "FK_ProfessionalServices_Professionals_ProfessionalId" FOREIGN KEY ("ProfessionalId") REFERENCES "Professionals" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProfessionalServices_Services_ServicesId" FOREIGN KEY ("ServicesId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    CREATE INDEX "IX_Professionals_IsActive" ON "Professionals" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    CREATE INDEX "IX_Professionals_Order" ON "Professionals" ("Order");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    CREATE INDEX "IX_ProfessionalServices_ServicesId" ON "ProfessionalServices" ("ServicesId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260705235620_AddProfessionals') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260705235620_AddProfessionals', '9.0.14');
    END IF;
END $EF$;
COMMIT;

