using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TTurnos.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddCampos : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Usar SQL idempotente para soportar DBs con estado parcialmente migrado

            // Bookings: cambiar CancelledAt a timestamp without time zone (si ya es ese tipo, no hace nada)
            migrationBuilder.Sql(@"
                ALTER TABLE ""Bookings""
                    ALTER COLUMN ""CancelledAt"" TYPE timestamp without time zone
                    USING ""CancelledAt""::timestamp without time zone;
            ");

            // Bookings: renombrar Vehicle -> Subject solo si Vehicle existe
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'Bookings' AND column_name = 'Vehicle'
                    ) THEN
                        ALTER TABLE ""Bookings"" RENAME COLUMN ""Vehicle"" TO ""Subject"";
                    END IF;
                END $$;
            ");

            // Bookings: agregar columnas si no existen
            migrationBuilder.Sql(@"ALTER TABLE ""Bookings"" ADD COLUMN IF NOT EXISTS ""CustomFieldsJson"" text;");
            migrationBuilder.Sql(@"ALTER TABLE ""Bookings"" ADD COLUMN IF NOT EXISTS ""Email"" text;");

            // Crear tabla NotificationLogs si no existe
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""NotificationLogs"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""BookingId"" integer NOT NULL,
                    ""EventType"" text NOT NULL,
                    ""Channel"" text NOT NULL,
                    ""Provider"" text NOT NULL,
                    ""Status"" text NOT NULL,
                    ""ProviderMessageId"" text,
                    ""ErrorMessage"" text,
                    ""RetryCount"" integer NOT NULL,
                    ""IsRetryable"" boolean NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    ""LastAttemptAt"" timestamp without time zone,
                    ""SentAt"" timestamp without time zone,
                    ""NextRetryAt"" timestamp without time zone,
                    CONSTRAINT ""PK_NotificationLogs"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_NotificationLogs_Bookings_BookingId""
                        FOREIGN KEY (""BookingId"") REFERENCES ""Bookings"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_BookingId"" ON ""NotificationLogs"" (""BookingId"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_NextRetryAt"" ON ""NotificationLogs"" (""NextRetryAt"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_NotificationLogs_Status"" ON ""NotificationLogs"" (""Status"");");

            // Crear tabla ContentVideos si no existe
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ContentVideos"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Title"" text NOT NULL,
                    ""VideoUrl"" text NOT NULL,
                    ""ThumbnailUrl"" text NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""Order"" integer NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""PK_ContentVideos"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ContentVideos_IsActive"" ON ""ContentVideos"" (""IsActive"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ContentVideos_Order"" ON ""ContentVideos"" (""Order"");");

            // Bookings: agregar CustomerEmailNormalized si no existe
            migrationBuilder.Sql(@"ALTER TABLE ""Bookings"" ADD COLUMN IF NOT EXISTS ""CustomerEmailNormalized"" text NOT NULL DEFAULT '';");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Bookings_CustomerEmailNormalized"" ON ""Bookings"" (""CustomerEmailNormalized"");");

            // Crear tabla ClientAccessCodes si no existe
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ClientAccessCodes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email"" text NOT NULL,
                    ""CodeHash"" text NOT NULL,
                    ""ExpiresAt"" timestamp without time zone NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    ""UsedAt"" timestamp without time zone,
                    CONSTRAINT ""PK_ClientAccessCodes"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ClientAccessCodes_Email"" ON ""ClientAccessCodes"" (""Email"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ClientAccessCodes_ExpiresAt"" ON ""ClientAccessCodes"" (""ExpiresAt"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "ClientAccessCodes");
            migrationBuilder.DropTable(name: "ContentVideos");
            migrationBuilder.DropTable(name: "NotificationLogs");

            migrationBuilder.DropIndex(name: "IX_Bookings_CustomerEmailNormalized", table: "Bookings");
            migrationBuilder.DropColumn(name: "CustomerEmailNormalized", table: "Bookings");
            migrationBuilder.DropColumn(name: "CustomFieldsJson", table: "Bookings");
            migrationBuilder.DropColumn(name: "Email", table: "Bookings");

            migrationBuilder.RenameColumn(
                name: "Subject",
                table: "Bookings",
                newName: "Vehicle");

            migrationBuilder.AlterColumn<DateTime>(
                name: "CancelledAt",
                table: "Bookings",
                type: "timestamp with time zone",
                nullable: true,
                oldClrType: typeof(DateTime),
                oldType: "timestamp without time zone",
                oldNullable: true);
        }
    }
}
