using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Turneo.Api.Migrations
{
    /// <inheritdoc />
    public partial class AddSiteConfigGalleryAndCustomFields : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Services: agregar CustomFieldsSchema (nuevo)
            migrationBuilder.AddColumn<string>(
                name: "CustomFieldsSchema",
                table: "Services",
                type: "jsonb",
                nullable: true);

            // Bookings: CustomerEmailNormalized — idempotente (puede ya existir de migración anterior)
            migrationBuilder.Sql(@"ALTER TABLE ""Bookings"" ADD COLUMN IF NOT EXISTS ""CustomerEmailNormalized"" text NOT NULL DEFAULT '';");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_Bookings_CustomerEmailNormalized"" ON ""Bookings"" (""CustomerEmailNormalized"");");

            // ClientAccessCodes — idempotente
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ClientAccessCodes"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Email"" text NOT NULL,
                    ""CodeHash"" text NOT NULL,
                    ""ExpiresAt"" timestamp without time zone NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    ""UsedAt"" timestamp without time zone,
                    CONSTRAINT ""PK_ClientAccessCodes"" PRIMARY KEY (""Id"")
                );
            ");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ClientAccessCodes_Email"" ON ""ClientAccessCodes"" (""Email"");");
            migrationBuilder.Sql(@"CREATE INDEX IF NOT EXISTS ""IX_ClientAccessCodes_ExpiresAt"" ON ""ClientAccessCodes"" (""ExpiresAt"");");

            // GalleryItems (nueva tabla)
            migrationBuilder.CreateTable(
                name: "GalleryItems",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    Tag = table.Column<string>(type: "text", nullable: false),
                    ImageUrl = table.Column<string>(type: "text", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    Order = table.Column<int>(type: "integer", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GalleryItems", x => x.Id);
                });

            // SiteConfigs (nueva tabla)
            migrationBuilder.CreateTable(
                name: "SiteConfigs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    BusinessName = table.Column<string>(type: "text", nullable: false),
                    WhatsAppNumber = table.Column<string>(type: "text", nullable: false),
                    InstagramUrl = table.Column<string>(type: "text", nullable: false),
                    InstagramHandle = table.Column<string>(type: "text", nullable: false),
                    Location = table.Column<string>(type: "text", nullable: false),
                    LocationShort = table.Column<string>(type: "text", nullable: false),
                    SiteUrl = table.Column<string>(type: "text", nullable: false),
                    LogoUrl = table.Column<string>(type: "text", nullable: false),
                    HeroTitle = table.Column<string>(type: "text", nullable: false),
                    HeroSubtitle = table.Column<string>(type: "text", nullable: false),
                    HeroBadge = table.Column<string>(type: "text", nullable: false),
                    MetaDescription = table.Column<string>(type: "text", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp without time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SiteConfigs", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_GalleryItems_IsActive",
                table: "GalleryItems",
                column: "IsActive");

            migrationBuilder.CreateIndex(
                name: "IX_GalleryItems_Order",
                table: "GalleryItems",
                column: "Order");

            // Seed de configuración inicial del negocio
           migrationBuilder.Sql(@"
            INSERT INTO ""SiteConfigs"" (
                ""BusinessName"", ""WhatsAppNumber"", ""InstagramUrl"", ""InstagramHandle"",
                ""Location"", ""LocationShort"", ""SiteUrl"", ""LogoUrl"",
                ""HeroTitle"", ""HeroSubtitle"", ""HeroBadge"", ""MetaDescription"", ""UpdatedAt""
            ) SELECT
                'Studio Nails & Beauty', '5491126920618', 'https://www.instagram.com/studionails', '@studionails',
                'Moreno, Zona Oeste, Buenos Aires', 'Moreno, Zona Oeste',
                'https://tu-sitio-nails.vercel.app', '/img/logo.png',
                'Turnos online para uñas y belleza',
                'Manicuría, esmaltado semipermanente, nail art y más.',
                'Belleza & Cuidado Personal',
                'Reservá tu turno online en nuestro estudio de uñas en Moreno.',
                NOW()
                WHERE NOT EXISTS (SELECT 1 FROM ""SiteConfigs"");
            ");

            // Seed de galería inicial
            migrationBuilder.Sql(@"
                INSERT INTO ""GalleryItems"" (""Title"", ""Tag"", ""ImageUrl"", ""IsActive"", ""Order"", ""CreatedAt"")
                SELECT v.title, v.tag, v.imageurl, v.isactive, v.ord, NOW()
                FROM (VALUES
                    ('Esmaltado Semipermanente', 'Manicuría', '/img/uñas1.png', true, 1),
                    ('Kapping Gel', 'Uñas', '/img/uñas2.png', true, 2),
                    ('Nail Art Diseño', 'Diseño', '/img/uñas3.png', true, 3),
                    ('Soft Gel Tips', 'Extensiones', '/img/uñas4.png', true, 4),
                    ('Spa de Manos', 'Cuidado', '/img/uñas5.png', true, 5)
                ) AS v(title, tag, imageurl, isactive, ord)
                WHERE NOT EXISTS (SELECT 1 FROM ""GalleryItems"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "GalleryItems");
            migrationBuilder.DropTable(name: "SiteConfigs");
            migrationBuilder.DropTable(name: "ClientAccessCodes");

            migrationBuilder.DropIndex(name: "IX_Bookings_CustomerEmailNormalized", table: "Bookings");
            migrationBuilder.DropColumn(name: "CustomerEmailNormalized", table: "Bookings");
            migrationBuilder.DropColumn(name: "CustomFieldsSchema", table: "Services");
        }
    }
}
